### ISSUE TITLE
map crashes

### ISSUE THREAD

**Issue by Raidboss-potato** [kmsraidboss/surf#10]
multiple maps cause the servers to reboot, no idea what the cause is, because these used to work.
BEGINNER
surf_year3000
surf_rebel_scaz_njv
MAIN SERVER
surf_antimatter_v2

**Comment by kmsraidboss** [comment]
after re-uploading each, none crashed the server after !nominating them then !rtving to change the map. surf_year3000 did crash my client once but i could rejoin the server and it loaded fine. this crash issue happens on some maps still after panorama update last year.
