### ISSUE TITLE
surf_ezpz_fifiedtion

### ISSUE THREAD

**Issue by Raidboss-potato** [kmsraidboss/surf#12]
-teleport behind spawn that allows for teleporting to very nearly the end of the map, resulting in the fastest route being to not do most of the map.

-map is linear on our server, but it's staged map.

Solution: Wipe times, rezone as a staged map. Zone off the teleport.

**Comment by kmsraidboss** [comment]
- Made start zone smaller
- Made 'stop' zones around 3 sides of the start zone so timer should stop if they leave the start zone area.
- Added stages 
- Reset regular map times
- Updated !tier info
- Updated for all 3 servers
