### ISSUE TITLE
beginner server surf_simpsons_refix

### ISSUE THREAD

**Issue by Raidboss-potato** [kmsraidboss/surf#9]
issues with boosts not working properly on stage 10, making the map unbeatable.

**Comment by kmsraidboss** [comment]
Haven't resolved the issue yet but I've tried the following with no success:

- replaced map file with one from easy surf
- tried skipping straight to stage 10 on easy +  skill surf to see if trigger filters exist that stop you from skipping stages, both servers the boost worked fine. 
- copied 'stripper' files for the map from easy surf to ensure consistency


Next steps I'll  take are:

- full file re-write for the entire server to ensure exact consistency with easy surf
- re-zone the map

**Comment by kmsraidboss** [comment]
I just did a full file re-write of the server, matching it with the other 2 surf servers, and it's now working correctly.
